spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
       eclipselink.ddl-generation: create-tables
       eclipselink.logging.level.sql: FINE
       eclipselink.logging.parameters: true
